[build]
target = "./index.html"
filehash = false

[watch]
ignore = []

[serve]
port = 1420
open = false
adress = "0.0.0.0"

[[hooks]]
stage = "pre_build"
command = "npm"
command_arguments = ["run", "build"]
