[build]
target = "./index.html"
filehash = false

[watch]
ignore = ["node_modules"]

[serve]
port = 3000
open = false
address = "0.0.0.0"

[[hooks]]
stage = "pre_build"
command = "npm"
command_arguments = ["run", "build"]


[hooks.windows]
stage = "pre_build"
command = "cmd"
command_arguments = ["/c", "npm", "run", "build"]
